### ISSUE TITLE
64bit incompatible

### ISSUE THREAD

**Issue by rezalas** [rezalas/riftshadow#1]
The current build will not run on a 64 bit OS in any fashion. I'm not sure the exact cause, but compilation will work yet execution will not. This needs to be solved fairly soon for build automation and deployment.

**Comment by rezalas** [comment]
Resolved using http://stackoverflow.com/questions/23317378/asm-volatile-issue-in-c-c-mud-code
Thanks to Mats Petersson!

This is far from trivial, since x86-64 uses register passing for arguments [and it's a rather ugly solution in the first place, since it's basically assuming no arguments are passed in registers, and that the callee function takes all arguments on the stack]. 
I would probably avoid the assembly version altogether, and instead of the second for-loop (with the assembly code) write something like:
switch(nArgs)
{
  case 0:
     (*funcptr)();
     break;
  case 1: 
     (*funcptr)(fptrs[0]);
     break;
  case 2:
     (*funcptr)(fptrs[0], fptrs[1]);
     break;
  ... Repeat until MAX_FUNCTION_ARGS is covered.
}     
It is unlikely to generate terribly bad code unless MAX_FUNCTION_ARGS is VERY large [in which case you probably want to change the calling convention of funcptr in the first place].

**Comment by rezalas** [comment]
There is another location with the same code. Funcptr and Queue both have this weird assembler issue. leaving bug open until we can resolve.

**Comment by IrishMidnight** [comment]
Don't wish to clutter a thread, so please delete if necessary.  Was curious if you're still working on this project in any fashion? I was Erifdel back in the day and although the player base was never huge, I had a lot of good memories.  That combined with wanting to mess around with code again and Riftshadow popped right to mind.

**Comment by rezalas** [comment]
Yes when I have time I'm still working on it. I have the domain active and I have continuous  integrations going with TravisCI, I just haven't had much time lately.

---
Paul M.


________________________________

**Comment by IrishMidnight** [comment]
forked a copy and figure my first personal task is seeing if I can get it to boot up and run locally.  I'm assuming that's possible in its current state?  Was looking at Cygwin perhaps to emulate an appropriate environment and feel like I've made that one work in the past on a ROT type derivative. However, advice certainly welcomed as in the long term I can hopefully help in some capacity (day-to-day life willing)

**Comment by rezalas** [comment]
Yes it will run locally. I suggest using VirtualBox and setting up a debian install which is what I've been testing development on. When you do you'll need to also set up the databases since it doesn't create them dynamically on load if not present, and inject both sql files. There is a day/night bug with mobs being visible at the wrong times you will likely experience. I haven't found how to properly fix that yet, but once that is fixed I'll open the public server again as it is fairly hard to play otherwise.
