### ISSUE TITLE
Inconsistent file paths in code lead to errors

### ISSUE THREAD

**Issue by forrcaho** [rezalas/riftshadow#10]
When built with the makefile, the executable lives in the `code` directory. Attempting to execute it from there gives me the following output:
```
*** Beginning RIFTSHADOW MUD server ***
Creating persistent SQL connection...
Loading options and greeting screen...
Loading class and race data...
Initializing host sockets...
Initialize random number generator...
Setting time, weather, and berus/calabren pos...
Assigning gsns and psns to skills and spells...
Reading the race info...
Sorting area list..
Loading area files..
Wed Oct 17 22:19:45 2018 :: Loading area files now...
area.lst: No such file or directory
```

It can't find `area` files, indicating that perhaps the code needs to be executed from the root directory.
However, executing `code/rift` from that directory gives the following output:

```
*** Beginning RIFTSHADOW MUD server ***
Creating persistent SQL connection...
Loading options and greeting screen...
Segmentation fault
```
This segfault is coming from line 392 of `bootup.c` which is an attempt to open a file identified by the macro `GREET_FILE`. We find this defined in `rift.h` as `"../area/login.txt"`

So: loading area files expects the code to be run from the project's root, but loading the greeting file expects the code to be run from the `code` subdirectory (and segfaults if it isn't).

This needs to be made consistent, and whatever is decided needs to be documented in the README.md.

**Comment by rezalas** [comment]
Great find! I've had to execute it from the area folder in the past to keep it stable enough to log into. I'm headed home from out of town so I'll get this approved asap.

---
Paul M.

________________________________

**Comment by rezalas** [comment]
I think the best fix for the log file is to relocate it to the root directory and if it doesn't exist have it created on demand. That way we don't run into the segfault on startup.

**Comment by forrcaho** [comment]
I was thinking that `RIFT_ROOT_DIR` could be defined in `rift.h` (as `"."`
if we want to run from root, or `".."` to run from code or another subdir,
or an absolute path) and go through the code and fix the paths to all files
(it _appears_ that a grep for "fopen" will find them all).

I started down that path, and I found there are places where absolute paths
under `/home/rift` are in the code, suggesting that originally the `rift`
user was set up not only as a db user, but also a system user. That
definitely needs to be fixed.

I can continue along this path (uh, pun intended?) if you think it's a good
idea, but it will likely take me a while; maybe I can get it done this
weekend sometime.

**Comment by forrcaho** [comment]
I was thinking that `RIFT_ROOT_DIR` could be defined in `rift.h` (as `"."`
if we want to run from root, or `".."` to run from code or another subdir,
or an absolute path) and go through the code and fix the paths to all files
(it _appears_ that a grep for "fopen" will find them all).

I started down that path, and I found there are places where absolute paths
under `/home/rift` are in the code, suggesting that originally the `rift`
user was set up not only as a db user, but also a system user. That
definitely needs to be fixed.

I can continue along this path (uh, pun intended?) if you think it's a good
idea, but it will likely take me a while; maybe I can get it done this
weekend sometime.

**Comment by rezalas** [comment]
It makes sense to me to run it from the stored root directory (I'm assuming it does for you as well) and then reference up to ./area/ etc., so that fix makes perfect sense to me. I believe you're right about the rift user having been an actual user as well as a sql user.

 We should definitely get rid of that so people can run this wherever they want to run it from and with whatever user their security levels they choose.

**Comment by rezalas** [comment]
What are you using for your debugging environment @forrcaho ? I'm wanting to improve my own and my setup is primarily for windows/vs

**Comment by forrcaho** [comment]
I'm on Debian linux, using gdb on the command line. Finding SIGSEGVs are really easy that way; I made a small screencast vid (1.1 Mb) example but I haven't figured out where to upload it.

You could probably use Windows Subsystem for Linux to do the same, if you're on Win 10.

**Comment by rezalas** [comment]
resolved previously by the ever-kind forrcaho
