### ISSUE TITLE
Unknown vnums reported at startup

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#129]
When `riftshadow` first starts, 3 bugs are reported related to unknown vnums.

```
... :: [*****] BUG: Read_object: vnum 16161 bad type.
... :: [*****] BUG: Read_object: vnum 16159 bad type.
... :: [*****] BUG: Read_object: vnum 16162 bad type.
```

These vnums look to be part of this file
https://github.com/rezalas/riftshadow/blob/65e9aa4e0f4273a08c80729d9f682659bf28e3de/area/valleydra.are#L703-L739

The common vnum among them is `ITEM_NOLOCATE`. It appears that the vnum is unhandled in the switch table here
https://github.com/rezalas/riftshadow/blob/65e9aa4e0f4273a08c80729d9f682659bf28e3de/code/db.c#L2239-L2326

**Comment by rezalas** [comment]
NoLocate is designed to prevent scrying detection, so I'm surprised to see it not supported but used. This zone was likely incomplete, so the creator (Steve) likely didn't know about the absence of support.

**Comment by sean-gilliam** [comment]
Cool beans. Just something that was nagging me every time I start riftshadow.
