### ISSUE TITLE
Cross-platform make file needed

### ISSUE THREAD

**Issue by rezalas** [rezalas/riftshadow#15]
Currently the project is restricted to Linux, but going cross platform and making it easier to test and work on is a priority, so a method for doing so needs to be selected be it cmake or some other.

**Comment by mrneo240** [comment]
Would Meson be acceptable? [https://mesonbuild.com/](https://mesonbuild.com/)

**Comment by rezalas** [comment]
Yes that would work well.

- Paul M.

________________________________

**Comment by rezalas** [comment]
cmake was selected by @sean-gilliam and works well at this time.
