### ISSUE TITLE
Remove the AIX specific pre-processor defines

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#154]
We can get rid of the AIX specific pre-processor defines in `merc.h` since, 
- Do we even have people playing on that platform that can test if it actually runs? 
- The current IBM docs look to handle the short type already [1].  The code was probably trying to deal with an older compiler.

[1] https://www.ibm.com/docs/en/ibm-mq/9.2?topic=platforms-standard-data-types-aix-linux-windows

**Comment by rezalas** [comment]
Given the age of `merc.h` I'm willing to bet your theory is accurate, as it pre-dates the actual game by more than a decade (see: [DikuMUD History Wiki](https://en.wikipedia.org/wiki/DikuMUD#Merc)).
