### ISSUE TITLE
Move header information into header file

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#16]
This project uses what appears to be old C++/98 style code. A lot of this code appears to be coded in C style. In order to modernize the project, we need to do a few things.

- [ ] Move macros out of the source file and into the source header file.
- [ ] Move `extern`s out of the source file and into the source header file.
- [ ] Move function definitions out of the source file and into the source header file.

This is only the beginning.

**Comment by mrneo240** [comment]
Need clarification. which files or just all source files?

**Comment by rezalas** [comment]
I believe all source files, though @sean-gilliam may be working on at least part of this.

**Comment by sean-gilliam** [comment]
Yea I'm currently working on this. Currently at around 75% or so. Major PITA.
