### ISSUE TITLE
Unused options loaded during boot sequence

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#172]
When the server goes through the boot sequence, there's a call to `RS.LoadOptions()`. This function is defined in the `bootup.c` file.

This function loads a configuration file located in `area/rc.conf` and populates three fields that aren't used or are defined elsewhere

- game_port 
- base_directory 
- player_dir

Propose we remove the function, the three unused fields and the unneeded options file.

**Comment by rezalas** [comment]
100% it needs to be removed, it's probably a stub from before.

**Comment by rezalas** [comment]
Addressed in PR #190
