### ISSUE TITLE
Possible missing code segment

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#173]
When the server goes through the boot sequence, there's a message displayed that indicates "Initializing host sockets...". However, there is no code associated with that and goes on to "Initialize random number generator..."

Wondering if the code was taken out but the message left in, or maybe some code got left out from the original.

For reference:
https://github.com/rezalas/riftshadow/blob/main/code/mud.c#L62-L64

```cpp
...
RS.Log("Initializing host sockets...");

<missing code block?>

RS.Log("Initialize random number generator...");
init_mm();
...
```

**Comment by rezalas** [comment]
This must have been an artifact that was never removed. We should dump it since the random number generator is plugged somewhere else.

**Comment by sean-gilliam** [comment]
Removed by commit ff471da547b9a904b7a34b93799f8c0307dadd81
