### ISSUE TITLE
Remove unneeded files

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#176]
Currently, in the codebase, there look to be several temporary or backup files that aren't needed or referenced by anything. We should look into removing these or possibly moving them to an `archive` folder to help with organization.

**Comment by rezalas** [comment]
That's a great point, I'll snag the dump files and move those and some of the others out that I know are never used.

**Comment by Psypher9** [comment]
@rezalas has this been handled already?

**Comment by Psypher9** [comment]
Is there a running list of these files? I may just not be seeing them.

**Comment by rezalas** [comment]
> Is there a running list of these files? I may just not be seeing them.

There's not an active list, but there are still files that we can prune that are not offering substance. For example:

- `area/CVS` : folder and subfiles I think are not used. We'd need to verify, but I don't think it's used for anything.
-  `bin/*.pl` : these may not actually be used at all. I could be wrong, but I've never used them. Maybe still useful but I'm not sure.

**Comment by sean-gilliam** [comment]
Some more

- `code/drift`: Looks like a build artifact from before we started with CMake/Ninja. Maybe an old rift executable.
- `code/learned`: looks to be some generated output from find or grep that isn't referenced by anything
- `code/progs.c`: isn't referenced by anything and only has one function declaration that is defined elsewhere.

**Comment by sean-gilliam** [comment]
Some more

- `area/.devrep.pl.swp`: looks like a vim swap file used for backups. Not needed.
- `area/.prog.lst.swp`: looks like a vim swap file used for backups. Not needed.
- `area/riftbuildstart.disabled`: looks to be a build artifact from before. Not needed.
- `area/riftstart`: looks to be a compiled program used to maybe start the service. But it's a binary of unknown origin, unknown function, and no documentation. Best to delete it.
- `area/riftstart.log`: looks to be the log file for the above program.
- `area/Sep-06.log`: blank log file not referenced by anything. Not needed.
- `area/Sep-07.log`: blank log file not referenced by anything. Not needed.
