### ISSUE TITLE
Catch 2.11.0 fails to build tests

### ISSUE THREAD

**Issue by Psypher9** [rezalas/riftshadow#177]
When running `make` for the full solution, the Catch 2 dependency fails to build resulting in the following errors

```cpp
.../tests/catch.hpp:10717:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10717 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
```
and
```cpp
/tests/catch.hpp:10776:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10776 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
```

These errors are directly addressed in an April 2021 release of Catch 2, found [here](https://github.com/catchorg/Catch2/releases/tag/v2.13.5). The original issue is [here](https://github.com/catchorg/Catch2/issues/2178).

Expected Behavior:
- I can run a full build with `make`
  - The tests build
  - The tests run and pass
-   Catch 2 is updated to the latest non-breaking version

**Comment by sean-gilliam** [comment]
Merged by #178
