### ISSUE TITLE
Group Character Classes into their own folder

### ISSUE THREAD

**Issue by Psypher9** [rezalas/riftshadow#184]
There appear to be several player class types that are all in the `code` directory with the rest of the project. It could be beneficial to group the character classes themselves into their own `code/characterClasses` directory for better organization.

Here are the classes I know of right now:

- [x] CClass: (class) - general Class functions
- [x] Druid
- [x] Healer
- [x] Necromancer: (necro)
- [x] Paladin
- [x] Anti-Paladin (ap)
- [x] Sorcerer
- [x] Thief
- [x] Warrior
- [x] Zealot
- [x] Chronomancer (chrono)

**Comment by sean-gilliam** [comment]
I believe Chronomancer (chrono) is another one.

**Comment by Psypher9** [comment]
Ah yes, you are right! I'll update the list

**Comment by Psypher9** [comment]
I have PR open for this now!
