### ISSUE TITLE
Segfault on mud school prog

### ISSUE THREAD

**Issue by cable2999** [rezalas/riftshadow#2]
I got this working on CentOS6 (plan is to move to CentOS7 soon), but am getting a segfault on the newbie prog somewhere.  I'll put my stuff into the forked repo I made, but I'm probably going to start making substantial changes to how some stuff works as soon as I get something stable-ish.

You shrug into a mage's torso armor.
You slip your legs into a mage's leggings.
You place a mage's boots on your feet.
You slip a mage's gloves onto your hands.
You slide a mage's armguards onto your arms.
You wield a steel dagger.
A steel dagger feels a little clumsy in your hands.
You wear an official Academy shield as a shield.
You have been equipped by the gods.
The Light of Creation
  Slowly, your eyes open, admitting the warm light of this new world.  You
find yourself awash in the sounds of the sea, as waves break against the
shore and gulls fly overhead -- you turn to watch them, and see nothing but
the light which surrounds you.  Subtly, the sound in the air shifts to
rustling leaves and a crackling fire; the scent of burning wood reaches you,
tickling you further toward consciousness.  As you become fully aware for
the first time, a booming voice strikes out through the white void: "Welcome
to Shalar, young pilgrim.  You have chosen to inhabit this vessel, and I
commend you for your choice.  In the coming minutes, you will become
accustomed to life here; I will guide you by placing signs with the
information you need.  You may look at the very first sign here in this
room.  Good luck -- I will be watching over you."  

[Exits: down]
     A sign winks into existence before you. (Type 'look sign' to view it.)
You have no unread notes.

<24hp 165m 292mv -> 
Onomath says 'Greetings, friend.  I have been sent to help you become acclimated to the perils of these lands, for the good-hearted must always be wary.'
Onomath now follows you.

<24hp 165m 292mv -> Connection closed by foreign host.

../code/rift 9999

*** Beginning RIFTSHADOW MUD server ***
Creating persistent SQL connection...
Loading options and greeting screen...
Loading class and race data...
Initializing host sockets...
Initialize random number generator...
Setting time, weather, and berus/calabren pos...
Assigning gsns and psns to skills and spells...
Reading the race info...
Sorting area list..
Loading area files..
Fri May 12 07:41:11 2017 :: Loading area files now...
Starting player file parsing..
Loading object counts off players now...
Object Limits loaded
Cabal Limits loaded
Exits fixed
Adjacent areas found
Notes cleaned
Fri May 12 07:41:11 2017 :: [*****] BUG: Read_object: vnum 16161 bad type.
Fri May 12 07:41:11 2017 :: [*****] BUG: Read_object: vnum 16159 bad type.
Fri May 12 07:41:11 2017 :: [*****] BUG: Read_object: vnum 16162 bad type.
Area update
Allocating gold
Cabal Items loaded
Priming weather
Fri May 12 07:41:11 2017 :: Riftshadow booted, binding on port 9999.
Fri May 12 07:41:15 2017 :: Sock.sinaddr:  127.0.0.1
Fri May 12 07:41:37 2017 :: Frulam@localhost new player.
Segmentation fault

**Comment by cable2999** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x0000000000461bcd in get_trust (ch=0x5c76a8) at handler.c:703
703	    if ( ch->desc != NULL && ch->desc->original != NULL )

Got this out of gdb.  Will try and track down.

**Comment by rezalas** [comment]
The entity that should be speaking is the guide mob (academy pet) for sure. I'll look at the mspec and see if I can figure out the reason the queued calls are throwing errors.

**Comment by rezalas** [comment]
I'm still not sure why, but it looks like when do_say is added to the queue the data is good (the mob that 'says' the words, the timer, the statement itself, and the number of arguments sent). However when called, the references pushed into do_say appear to be garbage. So I'm thinking this is memory related, maybe it's getting GCed during the timer? It shouldn't be that, but I'll keep looking. I may need to sit down with someone and pair it out.

**Comment by rezalas** [comment]
Issue resolved, queue was adding items but losing the proper pointers due to section called 'hack'.
