### ISSUE TITLE
Proposed auto labeling of PRs

### ISSUE THREAD

**Issue by Psypher9** [rezalas/riftshadow#207]
I can see that labeling issues is something that is being used to organize areas of work and I think that using an automatic labeling system could help provide insight to PR reviewers, at a high level, as to what areas of the application are being updated. 

[Here's the GitHub Labeler](https://github.com/actions/labeler), which is just a workflow and the configuration is defined in the repository being labeled.

We can set up labels that are assigned by file path match to quickly identify those areas. Also even after the PRs get merged, we'll still be able to view the label itself and see which issues and PRs it has been added to, so in a way it can also act as a quick topically organized historical reference. If we ever moved to using Releases, labels can also be used to auto organize generated release notes and produce sections within those notes.

I propose adding Labeler and getting a starter kit of labels configured. I'm happy to implement it.

**Comment by sean-gilliam** [comment]
@Psypher9 @rezalas FYI. It looks like the labeler is failing it's GitHub step on more recent PRs. Not sure what the cause of it is.

**Comment by Psypher9** [comment]
@sean-gilliam , yeah I saw. It's because I got the glob syntax wrong on `*.sql` and `*.sh`. I thought I had fixed it in my last PR, but this action only uses the `labeler.yml` configuration that is on `main` so it's a PR behind from getting updated.

I had made a similar configuration in another project, so I'll look back at what I did there and fix that today.  I'll make another issue
