### ISSUE TITLE
Internal Buglist Question

### ISSUE THREAD

**Issue by Psypher9** [rezalas/riftshadow#208]
As I'm looking through the SQL files, there is a `buglist` table that is tracking bugs. Do we want those ported to GitHub for triage?

**Comment by Psypher9** [comment]
Found in `rift.sql`

**Comment by rezalas** [comment]
Yeah it has an internal bug reporter that people can use inside the game. I’m not sure how many still exist, but yeah let's look at em

Thanks,
Paul McDowell
________________________________

**Comment by Psypher9** [comment]
I don't know, after looking at some of the content from these bugs, they don't seem to be that valuable. Mostly they're comments about balancing gameplay or just wholly unhelpful and not really anything to take action on.

_ALSO_, most of them are from 2002, so it really might not be that helpful to move to GitHub.

**Comment by rezalas** [comment]
Yeah sadly that's about the quality I remember when browsing them a long time ago. Some minor stuff related to maps, a few good ones about portals that didn't work, but overall I think people had a weak concept of what a bug was back then.
________________________________
