### ISSUE TITLE
Labeler Configuration Syntax Errors

### ISSUE THREAD

**Issue by Psypher9** [rezalas/riftshadow#217]
The Pull Request Labeler fails to run because of the bad glob syntax on SQL and Shell files. Here's the logs from latest failed execution:
```
The configuration file (path: .github/labeler.yml) isn't not found locally, fetching via the api
Error: YAMLException: unidentified alias "sql" (21:7)
```
and
```
Error: unidentified alias "sql" (21:7)
```

Expected behavior:
- The Pull Request Labeler can wrong without error

**Comment by rezalas** [comment]
Looks like we're rolling with the #220 PR!
