### ISSUE TITLE
Mudlet - After creating a new player host disconnects once acknowledging the MOTD

### ISSUE THREAD

**Issue by Psypher9** [rezalas/riftshadow#227]
I connected to Production with Mudlet and went through the process to make a new character that was:

- abyss
- warrior
- Neutral Evil
- Stats:
  -  Str: 22 
  - Int: 15
  - Wis: 16
  - Dex: 20 
  - Con: 21
- Starting Town: Cimar

After I saw the MOTD and the notes about submitting an application to be an immortal or to read the newbie help file, I was prompted to hit `Return` to continue.

I hit return and got this message:

![image](https://github.com/rezalas/riftshadow/assets/15854173/5eb79a30-41dd-4663-b034-7303b2bf6807)

**Comment by rezalas** [comment]
I noticed this and I seriously just reconnected because I didn't think about it before, but now that you mention it that's a bug that cropped up last year that I never worked on.

**Comment by sean-gilliam** [comment]
I wonder if this issue is related. #251

**Comment by rezalas** [comment]
> I wonder if this issue is related. #251

It might be, I remember looking at it and thinking it may be resolved but I didn't think about actually verifying and closing the issue.

**Comment by rezalas** [comment]
I just made a character on production and didn't get connected, so I believe we resolved it.
