### ISSUE TITLE
Config file ambiguity

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#228]
As of now, the repo contains two config files `config.json` and `area/rs.conf`. Both are read in when the server starts up. However, values from `config.json` are the only ones that appear to be used. 

Propose we remove the loading of the `area/rs.conf` file and delete the file. Not only will this get rid of unnecessary code; we get the added bonus of slightly increased bootup times.

**Comment by rezalas** [comment]
This and #229 are both good ones. I don't mind taking both if you're not set on it.

**Comment by sean-gilliam** [comment]
@rezalas Go for them both if you want.

**Comment by rezalas** [comment]
Associated #235
