### ISSUE TITLE
segmentation fault when trying to create a new player

### ISSUE THREAD

**Issue by danielw97** [rezalas/riftshadow#251]
Hi,
Thanks for your work on this project and making it compatible with modern systems.
I'm attempting to get it working, however when trying to create a new character I receive the following terminal output immediately after hitting enter after reading the motd:
 [*****] BUG: Save_char_obj: fopen                                               
 ../player/Graint.plr: No such file or directory                                 
 Segmentation fault                                                              
 This results in the mud crashing. Is there any way to get around this?
The ../player directory exists is there anything else I can try?
Running on Debian 12 and everything seems to build fine.
Let me know if there's any way I can help troubleshoot this.

**Comment by rezalas** [comment]
Nice catch, yes this is a bug we found recently after some refactoring. I believe @sean-gilliam  was working on resolving it. Do you see the file in the folder? The bug could be a case sensitivity issue with the file name. Can you post the generated name?

**Comment by danielw97** [comment]
Hi, thanks for the quick reply.
I don't see the filename in the folder, it looks as though it doesn't even get generated initially. I can try with uppercase and see what happens.

**Comment by sean-gilliam** [comment]
Try adding an empty file named `romtmp` to the `temp` folder in the base directory.

So say the base directory is `$HOME/src/riftshadow` then the file would be `$HOME/src/riftshadow/temp/romtmp`.

**Comment by sean-gilliam** [comment]
Might need to create a new character with a new name though since by that point I think it already wrote to the database.

**Comment by danielw97** [comment]
amazing, that seems to have fixed it, thanks to you both for replying so quickly.
 One last question, is there a way to elevate a player to admin status assuming there isn't a default one?

**Comment by sean-gilliam** [comment]
Sweet. As to elevating a player's status, @rezalas would know more about that.

**Comment by danielw97** [comment]
Hi again,
No rush on this of course, although one other thing I thought I would note.
I've just attempted to delete a player, however received the following error. It looks as though the game is trying to move a player file with essentially a nonsense name, see below with a line for context:
 Zarlan@192.168.15.1 has autoquit. [8 played, 10 (0) obj]                        
 mv: cannot stat '../player/'$'\r\337'']'$'\310\331''u.plr': No such file or dire
 ctory                                                                           
 Segmentation fault                                                              
 If this is something on my end let me know, as I'm happy to try a different os etc.

**Comment by sean-gilliam** [comment]
Those look like ASCII escape codes.

Looks like it's breaking on this line

https://github.com/rezalas/riftshadow/blob/7092ebc6f85b08e812cb9003d1b23ccc71630123/code/devextra.c#L767

in the `delete_char` method.

I noticed that when calling `delete_char` most methods wrap `name` in a call to `palloc_string` or `talloc_string`. Those methods might be mangling the name with uninitialized data.

**Comment by rezalas** [comment]
> o rush on this of course, although one other thing I thought I would note.
> I've just attempted to delete a player, however received the following error. It looks as though the game is trying to move a player file with essentially a nonsense name, see below with a line for context:
> Zarlan@192.168.15.1 has autoquit. [8 played, 10 (0) obj]
> mv: cannot stat '../player/'$'\r\337'']'$'\310\331''u.plr': No such file or dire
> ctory
> Segmentation fault
> If this is something on my end let me know, as I'm happy to try a different os etc.

Yes, Admin characters are immortals, and need their level set to 55 or higher. You can do this by logging out and manually modifying the level of the character saved in the player file.

**Comment by Psypher9** [comment]
Since #252 handled this can this be closed now?

**Comment by sean-gilliam** [comment]
I would say yes. We should make another issue regarding the delete character bug.

**Comment by rezalas** [comment]
I'm good with that.
