### ISSUE TITLE
Move db con info to a config file

### ISSUE THREAD

**Issue by rezalas** [rezalas/riftshadow#26]
right now the database info is stored in stdlibs/sql.h and in devextra.c and are compiled into the binary on build. It would be better if this info was moved to a config file that is read in on load.

- [ ] Create a config.json file located in the server app root
- [ ] Set up the configuration user, password, host, and database name in the config
- [ ] Modify the application to ingest this data at startup by adding a config loader / manager
- [ ] Set the SQL portion of the app to pull the connection data from the config manager

**Comment by sean-gilliam** [comment]
Credentials are also stored here https://github.com/rezalas/riftshadow/blob/master/code/devextra.c#L624-L627

**Comment by rezalas** [comment]
I've built the functionality for this over the last weekend, I'll be merging that up as soon as I can validate it tonight and make sure the other files pull it properly.

**Comment by rezalas** [comment]
Resolved, WOOHOO!!
