### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#27]
Currently there are no unit tests for this project. 

We need to identify key areas where unit tests are needed and create them.

**Comment by rezalas** [comment]
I'll take a look tonight and identify a few key areas to start with. The code is currently not easily tested with a number of globally scoped mutations throughout the code, so this will likely tie into multiple other issues.

**Comment by rezalas** [comment]
Looking back on this, we have unit tests now (thanks @sean-gilliam) though it's going to be an ongoing issue to add more and improve code coverage over time. I'm going to close this one since it's an ongoing enhancement at this point.
