### ISSUE TITLE
Day / Night cycle is flipped

### ISSUE THREAD

**Issue by rezalas** [rezalas/riftshadow#3]
The cycle for tracking what time is day vs night appears to be reversed somehow. Due to this, the mobs that should be outside during the day are not, and the mobs that should be hidden at night are not.

Ex. Mobs that should appear at night and not during the day (tagged nocturnal) are hidden at night. Mobs that should appear during the day (tagged diurnal) only appear at night. This means shop owners are only visible at night but their shop is closed at night, causing some serious confusion for shoppers.

**Comment by Psypher9** [comment]
Where would be a good location to start looking for this?

**Comment by rezalas** [comment]
It has something to do with the ACT_ tags and visibility I believe. The act_info.c file has a number of good leads surrounding ACT_NOCTURNAL and ACT_DIURNAL, and so does the update.c file (1076, 1087, 1774).

**Comment by rezalas** [comment]
This doesn't appear to be an issue still, not sure why...

**Comment by Psypher9** [comment]
BUY ITS WORKING!! YAY!!
