### ISSUE TITLE
buff typo

### ISSUE THREAD

**Issue by rezalas** [rezalas/riftshadow#35]
https://github.com/rezalas/riftshadow/blob/b563fd573e9b6110f338988792d396f8f1b07457/code/handler.c#L2916

this should be nocturnal

**Comment by JorgeAndd** [comment]
Can I work on this one?
Do I just need to fix the typo on the string?

**Comment by rezalas** [comment]
You can, you do, it's fixed! Feel free to grab another if you're up for more.
