### ISSUE TITLE
Unescaped system command

### ISSUE THREAD

**Issue by sean-gilliam** [rezalas/riftshadow#38]
In `olc_save.c`, there is an unescaped system command `mv` that is executed. If the file being moved contains spaces, then unintended results are bound to occur.
We should surround the file name (eg. `"/opt/riftshadow/area/file name"`) in quotes or escape the file name (eg. `/opt/riftshadow/area/file\ name`).

https://github.com/rezalas/riftshadow/blob/master/code/olc_save.c#L874-L875

```cpp
	sprintf(buf,"mv -f %s " RIFT_AREA_DIR "/backup/%s.bak", pArea->file_name, pArea->file_name);
	system(buf);
```

**Comment by sean-gilliam** [comment]
In `save.c`, there is an unescaped system command `gzip` that is executed. If the file being moved contains spaces, then unintended results are bound to occur.
We should surround the file name (eg. "/opt/riftshadow/save/file name") in quotes or escape the file name (eg. /opt/riftshadow/save/file\ name).

https://github.com/rezalas/riftshadow/blob/master/code/save.c#L840-L841
```cpp
	sprintf(buf,"gzip -dfq %s",strsave);
	system(buf);
```

**Comment by rezalas** [comment]
good point!

**Comment by rezalas** [comment]
This appears to have been resolved previously by @sean-gilliam
